Import('env')
Import('config')

source = [
    'main.cpp',
]

e = env.Clone()

e['LIBS'] = env['lib_list']

main = e.Program(config['output_bin']+'/xmlVerifier', source)

e.Depends(config['output_bin']+'/main/src/main.o', e['main_depends'])
e.Depends(main, e['main_depends'])
