Import('env')
Import('config')

source = [
    'XmlErrorReporter.cpp',
    'XmlNode.cpp',
    'XmlParser.cpp',
]

e = env.Clone()

# Generate Library
lib = e.Library(config['output_libs'] + '/xmlwrapper', source)

